/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AddInterface: typeof import('./src/components/AddInterface.vue')['default']
    AddParams: typeof import('./src/components/AddParams.vue')['default']
    AddResponse: typeof import('./src/components/AddResponse.vue')['default']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    EachPane: typeof import('./src/components/EachPane.vue')['default']
    EditMarkdown: typeof import('./src/components/EditMarkdown.vue')['default']
    InterfaceManager: typeof import('./src/components/InterfaceManager.vue')['default']
    MyCards: typeof import('./src/components/MyCards.vue')['default']
    MyTabs: typeof import('./src/components/MyTabs.vue')['default']
    PersonalSpace: typeof import('./src/components/PersonalSpace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    SpaceList: typeof import('./src/components/SpaceList.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TestCase: typeof import('./src/components/TestCase.vue')['default']
    ToolBtn: typeof import('./src/components/ToolBtn.vue')['default']
    UploadSwagger: typeof import('./src/components/UploadSwagger.vue')['default']
  }
}
